apiVersion: v1
kind: Service
metadata:
  name: pool-api-customer
spec:
  selector:
    app: pool-api-customer
  ports:
  - port: 8080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pool-api-customer
  labels:
    app: pool-api-customer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pool-api-customer
    spec:
      containers:
      - name: pool-api-customer
        image: mshatunov/pool-api-customer:latest
        ports:
        - containerPort: 8080
          protocol: TCP