apiVersion: v1
kind: Service
metadata:
  name: pool-infra-config-server
spec:
  selector:
    app: pool-infra-config-server
  ports:
  - port: 8888
    targetPort: 8888
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pool-infra-config-server
  labels:
    app: pool-infra-config-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pool-infra-config-server
    spec:
      containers:
      - name: pool-infra-config-server
        image: mshatunov/pool-infra-config-server:0.0.2
        ports:
        - containerPort: 8888
          protocol: TCP